export const CarouselDots = () => {
  return (
    <div className="absolute items-center box-border caret-transparent gap-x-2 flex justify-start pointer-events-none gap-y-2 w-full pr-16 left-6 bottom-8">
      <span className="relative bg-gray-200 box-border caret-transparent block h-2 w-2 overflow-hidden rounded-full after:accent-auto after:bg-red-600 after:caret-transparent after:text-white after:block after:text-xl after:not-italic after:normal-nums after:font-normal after:tracking-[0.0208px] after:leading-[30px] after:list-outside after:list-disc after:pointer-events-none after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-[0%] after:rounded-full after:border-separate after:left-0 after:inset-y-0 after:font-neue_haas_grotesk_display"></span>
      <span className="relative bg-gray-200 box-border caret-transparent block h-2 w-2 overflow-hidden rounded-full after:accent-auto after:bg-red-600 after:caret-transparent after:text-white after:block after:text-xl after:not-italic after:normal-nums after:font-normal after:tracking-[0.0208px] after:leading-[30px] after:list-outside after:list-disc after:pointer-events-none after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-[0%] after:rounded-full after:border-separate after:left-0 after:inset-y-0 after:font-neue_haas_grotesk_display"></span>
      <span className="relative bg-gray-200 box-border caret-transparent block h-2 w-2 overflow-hidden rounded-full after:accent-auto after:bg-red-600 after:caret-transparent after:text-white after:block after:text-xl after:not-italic after:normal-nums after:font-normal after:tracking-[0.0208px] after:leading-[30px] after:list-outside after:list-disc after:pointer-events-none after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-[0%] after:rounded-full after:border-separate after:left-0 after:inset-y-0 after:font-neue_haas_grotesk_display"></span>
      <span className="relative bg-gray-200 box-border caret-transparent block h-2 w-20 overflow-hidden rounded-full after:accent-auto after:bg-red-600 after:caret-transparent after:text-white after:block after:text-xl after:not-italic after:normal-nums after:font-normal after:tracking-[0.0208px] after:leading-[30px] after:list-outside after:list-disc after:pointer-events-none after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-[49.334%] after:rounded-full after:border-separate after:left-0 after:inset-y-0 after:font-neue_haas_grotesk_display"></span>
      <span className="relative bg-gray-200 box-border caret-transparent block h-2 w-2 overflow-hidden rounded-full after:accent-auto after:bg-red-600 after:caret-transparent after:text-white after:block after:text-xl after:not-italic after:normal-nums after:font-normal after:tracking-[0.0208px] after:leading-[30px] after:list-outside after:list-disc after:pointer-events-none after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-[0%] after:rounded-full after:border-separate after:left-0 after:inset-y-0 after:font-neue_haas_grotesk_display"></span>
    </div>
  );
};
